language: python
python:
          - "3.6"
script:
          - coverage run --source='.' manage.py test --settings=todo_list.settings.dev

env:
          - DJANGO=1.11 

install:
          - pip install -r requirements.txt

after_success:
          - coveralls
