# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-26 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priority',
            old_name='low',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='normal',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='urgent',
        ),
        migrations.AddField(
            model_name='task',
            name='changed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
