# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_todo_list', '0002_auto_20190826_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='event',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
